# AWS CodeBuild buildspec for Cloud Service Management System
# This buildspec provides equivalent functionality to GitHub Actions

version: 0.2

# Environment variables
env:
  variables:
    NODE_VERSION: "20"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - node --version
      - npm --version
  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      # Restore cache is handled by CodeBuild cache configuration
  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "Build completed with cached dependencies"
  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - echo "Running tests..."
      - echo "Build completed on `date`"

# Cache configuration
cache:
  paths:
    - '/root/.npm/**/*'
    - 'node_modules/**/*'

# Artifacts configuration (optional)
artifacts:
  files:
    - '**/*'
  name: build-output

# Reports configuration (optional)
# reports:
#   test-results:
#     files:
#       - 'test-results/*.xml'
#     file-format: 'JUNITXML'
