# Google Cloud Build configuration for Cloud Service Management System
# This configuration provides equivalent functionality to GitHub Actions

steps:
  # Checkout code (automatic in Cloud Build)

  # Setup Node.js and install dependencies
  - name: 'node:20'
    id: 'setup-node'
    entrypoint: 'node'
    args: ['--version']

  # Cache dependencies using Cloud Build cache
  - name: 'node:20'
    id: 'install-dependencies'
    entrypoint: 'npm'
    args: ['install']
    env:
      - 'NPM_CONFIG_CACHE=/workspace/.npm-cache'

  # Example build step
  - name: 'node:20'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Build completed with cached dependencies"

  # Run tests
  - name: 'node:20'
    id: 'test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running tests..."

# Configure caching for dependencies
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Cache configuration
cache:
  paths:
    - '/workspace/.npm-cache'
    - '/workspace/node_modules'

# Timeout configuration
timeout: '600s'

# Trigger configuration (configured via Cloud Build triggers UI or gcloud CLI)
# For reference, equivalent triggers would be:
# - Push to main branch
# - Pull requests to main branch
